# Generated by cpp11: do not edit by hand

sens_ <- function(e, lwr, upr, lwr_iter, upr_iter, grp, a, epsilon, eta, m, chunk_size, num_threads) {
  .Call(`_rar_sens_`, e, lwr, upr, lwr_iter, upr_iter, grp, a, epsilon, eta, m, chunk_size, num_threads)
}
