name: LTO bug fix

on: [push]

jobs:
  modify-and-commit:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Modify cpp11.cpp File
      run: |
        sed -i 's/extern SEXP run_testthat_tests(void \*);/extern SEXP run_testthat_tests(SEXP);/' src/cpp11.cpp

    - name: Check for Changes
      id: check_changes
      run: |
        git diff
        if git diff --quiet; then
          echo "No changes to commit"
          exit 0
        else
          echo "changes=true" >> $GITHUB_ENV
        fi

    - name: Commit and Push
      if: env.changes == 'true'
      env:
        NAME: Johann D. Gaebler
        EMAIL: me@jgaeb.com
      run: |
        git config --global user.name "$NAME"
        git config --global user.email "$EMAIL"
        git add src/cpp11.cpp
        git commit -m "Rewrite faulty signature in $GITHUB_SHA"
        git push

